import type { ApplicationLanguage } from "../applicationLanguage";

const zhMessages = {
  sagTitle: "SAG 记忆检索",
  sagDescription: "事件、实体与时序记忆的多路检索",
  graphTitle: "Graph RAG 图谱检索",
  graphDescription: "混合召回、关系扩展与路径解释",
  backendUnavailable: "OpenTopia 服务尚未连接。请稍后重试。",
  localServiceUnavailable: "本地服务尚未就绪。",
  eyebrow: "资料库",
  title: "知识与记忆检索",
  subtitle: "选择检索后端，构造并审阅独立的上下文包",
  connected: "服务已连接",
  starting: "正在启动",
  attention: "需要处理",
  refresh: "刷新",
  boundaryAria: "集成边界",
  reviewMode: "审阅模式",
  boundaryDetail: "当前只构造待审上下文包，不写入提示词，也不改变智能体循环。",
  promptOff: "提示词注入：关闭",
  cannotConnect: "无法连接",
  restart: "重新启动",
  recheck: "重新检测",
  features: "资料库功能",
  searchReview: "检索审阅",
  sources: "资料来源",
  incrementalImport: "增量导入",
  retrievalBackend: "检索后端",
  chooseBackendAria: "选择资料库检索后端",
  current: "当前使用",
  available: "可选择",
  sagOverviewAria: "SAG 索引概览",
  graphOverviewAria: "Graph RAG 索引概览",
  sourceCount: "资料源",
  evidenceBlocks: "证据块",
  events: "事件",
  entities: "实体",
  indexedDocuments: "文档（索引总量）",
  chunks: "分块",
  relations: "关系",
  vectorBackend: "向量后端",
  indexVersion: "索引版本",
  unknown: "未知",
  searchQuestion: "检索问题",
  sagQueryPlaceholder: "例如：用户现在对多平台发布格式的偏好是什么？",
  graphQueryPlaceholder: "例如：从发布规范出发，关联的审核与分发规则是什么？",
  namespaceOptional: "命名空间（可选）",
  retrievalMode: "检索方式",
  graphRetrievalModeAria: "Graph RAG 检索方式",
  automatic: "自动",
  hybrid: "混合",
  graphExpansion: "图扩展",
  candidateCount: "候选数量",
  contextBudget: "上下文 Token 预算",
  deepseekPlanning: "DeepSeek 规划",
  deepseekDetail: "拆解证据需求并辅助多路检索",
  pathExplanation: "关系路径解释",
  pathExplanationDetail: "展示种子文档、扩展节点与关系类型",
  searching: "正在检索",
  buildContextPack: "构造上下文包",
  noContextPack: "尚未构造上下文包",
  sagEmptyDetail: "输入问题后，可以查看多路检索命中的证据块及其选择原因。",
  graphEmptyDetail: "输入问题后，可以查看混合检索种子、图扩展证据和关系路径。",
  reviewContextPack: "待审上下文包",
  blockUnit: "个证据块",
  elapsed: "耗时",
  seconds: "秒",
  tokenEstimate: "Token 估算",
  draft: "草稿",
  retrievalPlan: "检索规划 / 证据需求",
  anyTime: "任意时间",
  covered: "已覆盖",
  notCovered: "未覆盖",
  evidenceAria: "命中证据块",
  source: "来源：",
  selectionReason: "选择原因：",
  approximately: "约",
  tokens: "tokens",
  graphPaths: "图路径",
  pathUnit: "条",
  graphExpanded: "已执行图扩展",
  hybridOnly: "仅混合检索",
  graphDecision: "检索判定与图路径",
  confidence: "置信度",
  noGraphPath: "本次没有产生关系扩展路径。",
  graphEvidenceAria: "Graph RAG 命中证据块",
  graphMatch: "图关系扩展命中",
  hybridMatch: "关键词与向量混合命中",
  lexicalScore: "关键词分数：",
  denseScore: "向量分数：",
  path: "路径：",
  matchingItems: "条匹配",
  visibleItems: "条可见",
  reading: "读取中",
  loadedSources: "已加载资料",
  filterSources: "筛选资料",
  sagFilterPlaceholder: "标题、文件名、命名空间或来源键",
  graphFilterPlaceholder: "标题、文档 ID、业务分类或负责人",
  visibleIdentityPrefix: "当前身份可见",
  indexTotalPrefix: "条；Graph RAG 索引总量为",
  itemSuffix: "条。",
  browseAfterConnect: "资料库服务连接后可浏览来源。",
  retry: "重试",
  loadingSources: "正在读取资料列表…",
  sourceList: "资料来源列表",
  noSourceAddress: "无来源地址",
  pagePrefix: "第",
  pageMiddle: "条，共",
  pageSuffix: "条",
  previous: "上一页",
  next: "下一页",
  noMatches: "没有匹配资料",
  noVisibleSources: "当前身份没有可见资料",
  changeFilter: "换一个筛选条件。",
  addFirstPrefix: "通过增量导入添加第一份",
  addFirstSuffix: "资料。",
  upsertTitle: "新增或更新",
  sagIngestDetail: "相同来源键会创建新版本并切换活动投影，不需要全量重建索引。",
  graphIngestDetail:
    "相同文档 ID 会更新对应文档投影，并和关系图使用同一索引版本发布。",
  chooseFile: "选择资料文件",
  supportedFiles: "支持 PDF、DOCX、PPTX、XLSX、HTML、Markdown 和 TXT",
  titleHint: "留空时使用文件内标题或文件名",
  sourceTitle: "资料标题",
  namespace: "命名空间",
  businessClass: "业务分类",
  sagSourceKeyHint: "再次上传相同来源键即执行增量版本更新",
  graphDocumentIdHint: "作为稳定文档 ID；再次上传会更新同一文档",
  stableSourceKey: "稳定来源键（可选）",
  stableDocumentId: "稳定文档 ID（可选）",
  sagMetadataHint: 'JSON 对象，例如 {"department":"sales"}',
  graphMetadataHint: "可设置 owner、allowed_roles、sensitivity 和 version",
  metadataOptional: "业务元数据（可选）",
  indexing: "正在分块并构建增量索引",
  import: "导入",
  unchanged: "资料内容未变化",
  published: "资料已发布",
  indexed: "资料已索引",
  chunkUnit: "个分块",
  routeRag: "知识检索",
  routeExact: "精确检索",
  routeTool: "工具路由（仅用于判定）",
  routeHandoff: "转交或拒答路由（仅用于判定）",
  relationReferences: "引用",
  relationSupersedes: "替代",
  relationRelated: "相关",
} as const;

export type LibraryMessageKey = keyof typeof zhMessages;

const enMessages: Record<LibraryMessageKey, string> = {
  sagTitle: "SAG memory retrieval",
  sagDescription:
    "Multi-path retrieval across events, entities, and temporal memory",
  graphTitle: "Graph RAG retrieval",
  graphDescription:
    "Hybrid recall, relationship expansion, and path explanations",
  backendUnavailable:
    "The OpenTopia service is not connected. Try again later.",
  localServiceUnavailable: "The local service is not ready.",
  eyebrow: "Library",
  title: "Knowledge and memory retrieval",
  subtitle:
    "Choose a retrieval backend, then build and review an isolated context pack",
  connected: "Service connected",
  starting: "Starting",
  attention: "Needs attention",
  refresh: "Refresh",
  boundaryAria: "Integration boundary",
  reviewMode: "Review mode",
  boundaryDetail:
    "This only builds a context pack for review. It does not inject prompts or change the agent loop.",
  promptOff: "Prompt injection: Off",
  cannotConnect: "Unable to connect to",
  restart: "Restart",
  recheck: "Check again",
  features: "library features",
  searchReview: "Search and review",
  sources: "Sources",
  incrementalImport: "Incremental import",
  retrievalBackend: "Retrieval backend",
  chooseBackendAria: "Choose a library retrieval backend",
  current: "In use",
  available: "Available",
  sagOverviewAria: "SAG index overview",
  graphOverviewAria: "Graph RAG index overview",
  sourceCount: "Sources",
  evidenceBlocks: "Evidence blocks",
  events: "Events",
  entities: "Entities",
  indexedDocuments: "Documents (index total)",
  chunks: "Chunks",
  relations: "Relationships",
  vectorBackend: "Vector backend",
  indexVersion: "Index version",
  unknown: "Unknown",
  searchQuestion: "Search question",
  sagQueryPlaceholder:
    "For example: What are the user's current preferences for cross-platform publishing formats?",
  graphQueryPlaceholder:
    "For example: Starting from the publishing policy, which review and distribution rules are related?",
  namespaceOptional: "Namespace (optional)",
  retrievalMode: "Retrieval mode",
  graphRetrievalModeAria: "Graph RAG retrieval mode",
  automatic: "Auto",
  hybrid: "Hybrid",
  graphExpansion: "Graph expansion",
  candidateCount: "Candidates",
  contextBudget: "Context token budget",
  deepseekPlanning: "DeepSeek planning",
  deepseekDetail: "Decompose evidence needs and assist multi-path retrieval",
  pathExplanation: "Relationship path explanation",
  pathExplanationDetail:
    "Show seed documents, expanded nodes, and relationship types",
  searching: "Searching",
  buildContextPack: "Build context pack",
  noContextPack: "No context pack built yet",
  sagEmptyDetail:
    "Enter a question to review matched evidence blocks and why they were selected.",
  graphEmptyDetail:
    "Enter a question to review hybrid seeds, graph-expanded evidence, and relationship paths.",
  reviewContextPack: "Context pack for review",
  blockUnit: "evidence blocks",
  elapsed: "Elapsed",
  seconds: "seconds",
  tokenEstimate: "Token estimate",
  draft: "Draft",
  retrievalPlan: "Retrieval plan / Evidence needs",
  anyTime: "Any time",
  covered: "Covered",
  notCovered: "Not covered",
  evidenceAria: "Matched evidence blocks",
  source: "Source: ",
  selectionReason: "Selection reason: ",
  approximately: "About",
  tokens: "tokens",
  graphPaths: "Graph paths",
  pathUnit: "paths",
  graphExpanded: "Graph expansion used",
  hybridOnly: "Hybrid retrieval only",
  graphDecision: "Retrieval decision and graph paths",
  confidence: "Confidence",
  noGraphPath: "No relationship-expansion path was produced.",
  graphEvidenceAria: "Graph RAG matched evidence blocks",
  graphMatch: "Matched through graph expansion",
  hybridMatch: "Matched through keyword and vector retrieval",
  lexicalScore: "Lexical score: ",
  denseScore: "Vector score: ",
  path: "Path: ",
  matchingItems: "matches",
  visibleItems: "visible",
  reading: "Loading",
  loadedSources: "Loaded sources",
  filterSources: "Filter sources",
  sagFilterPlaceholder: "Title, filename, namespace, or source key",
  graphFilterPlaceholder: "Title, document ID, business class, or owner",
  visibleIdentityPrefix: "Visible to the current identity:",
  indexTotalPrefix: "; total documents in the Graph RAG index:",
  itemSuffix: ".",
  browseAfterConnect: "Connect the library service to browse sources.",
  retry: "Retry",
  loadingSources: "Loading the source list…",
  sourceList: "source list",
  noSourceAddress: "No source address",
  pagePrefix: "Items",
  pageMiddle: "of",
  pageSuffix: "",
  previous: "Previous",
  next: "Next",
  noMatches: "No matching sources",
  noVisibleSources: "No sources are visible to the current identity",
  changeFilter: "Try a different filter.",
  addFirstPrefix: "Use incremental import to add the first",
  addFirstSuffix: "source.",
  upsertTitle: "Add or update",
  sagIngestDetail:
    "Uploading the same source key creates a new version and switches the active projection without rebuilding the full index.",
  graphIngestDetail:
    "Uploading the same document ID updates its projection and publishes it with the relationship graph under one index version.",
  chooseFile: "Choose a source file",
  supportedFiles: "Supports PDF, DOCX, PPTX, XLSX, HTML, Markdown, and TXT",
  titleHint: "Leave blank to use the title in the file or its filename",
  sourceTitle: "Source title",
  namespace: "Namespace",
  businessClass: "Business class",
  sagSourceKeyHint:
    "Upload the same source key again to create an incremental version",
  graphDocumentIdHint:
    "Used as a stable document ID; uploading again updates the same document",
  stableSourceKey: "Stable source key (optional)",
  stableDocumentId: "Stable document ID (optional)",
  sagMetadataHint: 'JSON object, for example {"department":"sales"}',
  graphMetadataHint: "Supports owner, allowed_roles, sensitivity, and version",
  metadataOptional: "Business metadata (optional)",
  indexing: "Chunking and building the incremental index",
  import: "Import",
  unchanged: "Source content is unchanged",
  published: "Source published",
  indexed: "Source indexed",
  chunkUnit: "chunks",
  routeRag: "Knowledge retrieval",
  routeExact: "Exact search",
  routeTool: "Tool route (decision only)",
  routeHandoff: "Handoff or refusal route (decision only)",
  relationReferences: "References",
  relationSupersedes: "Supersedes",
  relationRelated: "Related",
};

export function libraryMessage(
  language: ApplicationLanguage,
  key: LibraryMessageKey,
): string {
  return (language === "en-US" ? enMessages : zhMessages)[key];
}
